@extends('layouts.app', ['title' => 'Configuración', 'heading' => 'Configura tu restaurante'])

@php
    $days = [1 => 'Lunes', 2 => 'Martes', 3 => 'Miércoles', 4 => 'Jueves', 5 => 'Viernes', 6 => 'Sábado', 7 => 'Domingo'];
    $contexts = ['general' => 'Horario general', 'takeaway' => 'Take Away', 'delivery' => 'Delivery'];
    $timezones = ['Europe/Madrid' => 'España · Madrid', 'Atlantic/Canary' => 'España · Canarias', 'Europe/Lisbon' => 'Portugal · Lisboa', 'UTC' => 'UTC'];
@endphp

@section('content')
    <div class="max-w-5xl">
        <p class="max-w-3xl text-lg leading-8 text-stone-600">Actualiza los datos, modalidades de pedido y horarios de <span class="font-semibold text-stone-900">{{ $restaurant->name }}</span> desde un único lugar, sin mezclar opciones que todavía no necesitas.</p>

        @if (session('status'))
            <div class="mt-6 flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800" role="status">
                <span class="flex size-6 items-center justify-center rounded-full bg-emerald-600 text-xs text-white">✓</span>
                {{ session('status') }}
                     </div>
        @endif

        <div class="mt-8 grid gap-8 lg:grid-cols-[180px_minmax(0,1fr)] lg:items-start">
            <nav class="settings-tabs flex gap-2 overflow-x-auto pb-1 lg:sticky lg:top-6 lg:block lg:space-y-1" aria-label="Configuración del restaurante">
                <a href="#general" class="settings-tab">Datos generales</a>
                <a href="#channels" class="settings-tab">Canales</a>
                <a href="#hours" class="settings-tab">Horarios</a>
            </nav>

            <div class="space-y-8">
                <form id="general-form" data-dirty-form method="POST" action="{{ route('restaurant.settings.details.update', $restaurant) }}" class="settings-card scroll-mt-6">
                    @csrf @method('PATCH')
                    <div class="settings-card-header" id="general">
                        <div><p class="eyebrow">Identidad y contacto</p><h2 class="settings-title">Datos generales</h2><p class="settings-description">La información básica que identifica a tu establecimiento.</p></div>
                    </div>
                    @if ($errors->any())
                        <div class="mx-6 mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert"><strong>Revisa los datos introducidos.</strong> Hay campos que necesitan tu atención.</div>
                    @endif
                    <div class="settings-card-body grid gap-5 sm:grid-cols-2">
                        <div class="sm:col-span-2"><label for="name" class="field-label">Nombre comercial <span class="text-orange-600">*</span></label><input id="name" name="name" value="{{ old('name', $restaurant->name) }}" required class="form-input @error('name') field-error @enderror">@error('name')<p class="field-message">{{ $message }}</p>@enderror</div>
                        <div><label for="establishment_type" class="field-label">Tipo de establecimiento</label><select id="establishment_type" name="establishment_type" class="form-input"><option value="">Selecciona una opción</option>@foreach ($establishmentTypes as $value => $label)<option value="{{ $value }}" @selected(old('establishment_type', $restaurant->establishment_type) === $value)>{{ $label }}</option>@endforeach</select></div>
                        <div><label for="contact_email" class="field-label">Email de contacto</label><input id="contact_email" name="contact_email" type="email" value="{{ old('contact_email', $restaurant->contact_email) }}" class="form-input">@error('contact_email')<p class="field-message">{{ $message }}</p>@enderror</div>
                        <div><label for="phone" class="field-label">Teléfono principal</label><input id="phone" name="phone" value="{{ old('phone', $restaurant->phone) }}" class="form-input"></div>
                        <div><label for="secondary_phone" class="field-label">Teléfono secundario</label><input id="secondary_phone" name="secondary_phone" value="{{ old('secondary_phone', $restaurant->secondary_phone) }}" class="form-input"></div>
                        <div class="sm:col-span-2"><label for="description" class="field-label">Descripción</label><textarea id="description" name="description" rows="3" class="form-input">{{ old('description', $restaurant->description) }}</textarea></div>
                        <div><label for="website" class="field-label">Web</label><input id="website" name="website" type="url" placeholder="https://" value="{{ old('website', $restaurant->website) }}" class="form-input">@error('website')<p class="field-message">{{ $message }}</p>@enderror</div>
                        <div><label for="instagram" class="field-label">Instagram</label><input id="instagram" name="instagram" placeholder="@tu-restaurante" value="{{ old('instagram', $restaurant->instagram) }}" class="form-input"></div>
                        <div><label for="facebook" class="field-label">Facebook</label><input id="facebook" name="facebook" value="{{ old('facebook', $restaurant->facebook) }}" class="form-input"></div>
                        <div><label for="tiktok" class="field-label">TikTok</label><input id="tiktok" name="tiktok" value="{{ old('tiktok', $restaurant->tiktok) }}" class="form-input"></div>
                    </div>
                    <div class="settings-subsection"><p class="eyebrow">Ubicación</p><h3 class="mt-1 text-base font-semibold">Dónde encontrarte</h3><div class="mt-5 grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label for="address" class="field-label">Dirección</label><input id="address" name="address" value="{{ old('address', $restaurant->address) }}" class="form-input"></div><div><label for="postal_code" class="field-label">Código postal</label><input id="postal_code" name="postal_code" value="{{ old('postal_code', $restaurant->postal_code) }}" class="form-input"></div><div><label for="city" class="field-label">Localidad</label><input id="city" name="city" value="{{ old('city', $restaurant->city) }}" class="form-input"></div><div><label for="province" class="field-label">Provincia</label><input id="province" name="province" value="{{ old('province', $restaurant->province) }}" class="form-input"></div><div><label for="country" class="field-label">País</label><input id="country" name="country" value="{{ old('country', $restaurant->country) }}" required class="form-input"></div><div><label for="timezone" class="field-label">Zona horaria</label><select id="timezone" name="timezone" class="form-input">@foreach ($timezones as $value => $label)<option value="{{ $value }}" @selected(old('timezone', $restaurant->timezone) === $value)>{{ $label }}</option>@endforeach</select></div><div class="grid grid-cols-2 gap-3"><div><label for="latitude" class="field-label">Latitud</label><input id="latitude" name="latitude" inputmode="decimal" value="{{ old('latitude', $restaurant->latitude) }}" class="form-input"></div><div><label for="longitude" class="field-label">Longitud</label><input id="longitude" name="longitude" inputmode="decimal" value="{{ old('longitude', $restaurant->longitude) }}" class="form-input"></div></div></div></div>
                    <div class="settings-subsection"><p class="eyebrow">Fiscal y tickets</p><h3 class="mt-1 text-base font-semibold">Información para futuras ventas</h3><div class="mt-5 grid gap-5 sm:grid-cols-2"><div><label for="legal_name" class="field-label">Razón social</label><input id="legal_name" name="legal_name" value="{{ old('legal_name', $restaurant->legal_name) }}" class="form-input"></div><div><label for="tax_id" class="field-label">NIF / CIF</label><input id="tax_id" name="tax_id" value="{{ old('tax_id', $restaurant->tax_id) }}" class="form-input"></div><div><label for="default_vat" class="field-label">IVA por defecto (%)</label><input id="default_vat" name="default_vat" type="number" step="0.01" min="0" max="100" value="{{ old('default_vat', $restaurant->default_vat) }}" class="form-input"></div><div class="sm:col-span-2"><label for="ticket_footer" class="field-label">Texto adicional del ticket</label><textarea id="ticket_footer" name="ticket_footer" rows="2" class="form-input">{{ old('ticket_footer', $restaurant->ticket_footer) }}</textarea></div></div></div>
                    <div class="settings-card-footer"><span class="form-dirty-label hidden">Cambios sin guardar</span><button type="submit" class="button-primary">Guardar datos</button></div>
                </form>

                <form id="channels-form" data-dirty-form method="POST" action="{{ route('restaurant.settings.channels.update', $restaurant) }}" class="settings-card scroll-mt-6">
                    @csrf @method('PATCH')
                    <div class="settings-card-header" id="channels"><div><p class="eyebrow">Cómo trabajas</p><h2 class="settings-title">Canales de venta</h2><p class="settings-description">Activa solo las modalidades que tu restaurante ofrece ahora.</p></div></div>
                     <div class="settings-card-body space-y-4">
                         <div class="rounded-2xl border border-stone-200 bg-stone-50 p-4"><p class="font-semibold">Pedidos públicos</p><div class="mt-3 grid gap-3 sm:grid-cols-2"><label class="check-label"><input type="checkbox" name="public_menu_enabled" value="1" @checked(old('public_menu_enabled', $restaurant->public_menu_enabled))> Carta pública visible</label><label class="check-label"><input type="checkbox" name="qr_ordering_enabled" value="1" @checked(old('qr_ordering_enabled', $restaurant->qr_ordering_enabled))> Permitir pedidos QR</label><div><label class="field-label">Aceptación QR</label><select class="form-input" name="qr_acceptance_mode"><option value="manual" @selected(old('qr_acceptance_mode', $restaurant->qr_acceptance_mode) === 'manual')>Manual</option><option value="automatic" @selected(old('qr_acceptance_mode', $restaurant->qr_acceptance_mode) === 'automatic')>Automática</option></select></div><div><label class="field-label">Aceptación Take Away</label><select class="form-input" name="takeaway_acceptance_mode"><option value="manual" @selected(old('takeaway_acceptance_mode', $restaurant->takeaway_acceptance_mode) === 'manual')>Manual</option><option value="automatic" @selected(old('takeaway_acceptance_mode', $restaurant->takeaway_acceptance_mode) === 'automatic')>Automática</option></select></div><div><label class="field-label">Aceptación Delivery</label><select class="form-input" name="delivery_acceptance_mode"><option value="manual" @selected(old('delivery_acceptance_mode', $restaurant->delivery_acceptance_mode) === 'manual')>Manual</option><option value="automatic" @selected(old('delivery_acceptance_mode', $restaurant->delivery_acceptance_mode) === 'automatic')>Automática</option></select></div></div></div>
                        <label class="channel-card"><input type="checkbox" name="dine_in_enabled" value="1" @checked(old('dine_in_enabled', $restaurant->dine_in_enabled)) class="toggle-input"><span><strong>Consumo en local</strong><small>El restaurante atiende a clientes en el establecimiento.</small></span></label>
                        <div class="channel-card-wrap"><label class="channel-card"><input type="checkbox" name="takeaway_enabled" value="1" data-toggle-target="takeaway-options" @checked(old('takeaway_enabled', $restaurant->takeaway_enabled)) class="toggle-input"><span><strong>Take Away</strong><small>Los clientes pueden recoger sus pedidos en el restaurante.</small></span></label><div id="takeaway-options" class="channel-options" @if (!old('takeaway_enabled', $restaurant->takeaway_enabled)) hidden @endif><div><label for="takeaway_prep_minutes" class="field-label">Tiempo estimado de preparación (minutos)</label><input id="takeaway_prep_minutes" name="takeaway_prep_minutes" type="number" min="1" max="240" value="{{ old('takeaway_prep_minutes', $restaurant->takeaway_prep_minutes) }}" class="form-input max-w-xs"></div><label class="check-label"><input type="checkbox" name="takeaway_use_general_schedule" value="1" @checked(old('takeaway_use_general_schedule', $restaurant->takeaway_use_general_schedule))> Usar el horario general</label><p class="field-help">Desactívalo si Take Away necesita un horario propio.</p></div></div>
                        <div class="channel-card-wrap"><label class="channel-card"><input type="checkbox" name="delivery_enabled" value="1" data-toggle-target="delivery-options" @checked(old('delivery_enabled', $restaurant->delivery_enabled)) class="toggle-input"><span><strong>Delivery</strong><small>El restaurante prepara y entrega pedidos a domicilio.</small></span></label><div id="delivery-options" class="channel-options" @if (!old('delivery_enabled', $restaurant->delivery_enabled)) hidden @endif><div class="grid gap-5 sm:grid-cols-2"><div><label for="delivery_radius_km" class="field-label">Radio máximo (km)</label><input id="delivery_radius_km" name="delivery_radius_km" type="number" step="0.1" min="0.1" max="500" value="{{ old('delivery_radius_km', $restaurant->delivery_radius_km) }}" class="form-input"></div><div><label for="delivery_fee" class="field-label">Coste de reparto (€)</label><input id="delivery_fee" name="delivery_fee" type="number" step="0.01" min="0" value="{{ old('delivery_fee', $restaurant->delivery_fee) }}" class="form-input"></div><div><label for="delivery_minimum_order" class="field-label">Pedido mínimo (€)</label><input id="delivery_minimum_order" name="delivery_minimum_order" type="number" step="0.01" min="0" value="{{ old('delivery_minimum_order', $restaurant->delivery_minimum_order) }}" class="form-input"></div><div><label for="delivery_prep_minutes" class="field-label">Tiempo estimado (minutos)</label><input id="delivery_prep_minutes" name="delivery_prep_minutes" type="number" min="1" max="240" value="{{ old('delivery_prep_minutes', $restaurant->delivery_prep_minutes) }}" class="form-input"></div></div><label class="check-label"><input type="checkbox" name="delivery_use_general_schedule" value="1" @checked(old('delivery_use_general_schedule', $restaurant->delivery_use_general_schedule))> Usar el horario general</label><p class="field-help">Desactívalo si Delivery necesita un horario propio.</p></div></div>
                    </div>
                    <div class="settings-card-footer"><span class="form-dirty-label hidden">Cambios sin guardar</span><button type="submit" class="button-primary">Guardar canales</button></div>
                </form>

                <form id="hours-form" data-dirty-form method="POST" action="{{ route('restaurant.settings.hours.update', $restaurant) }}" class="settings-card scroll-mt-6" data-schedule-form>
                    @csrf @method('PUT')
                    <div class="settings-card-header" id="hours"><div><p class="eyebrow">Cuándo operas</p><h2 class="settings-title">Horarios</h2><p class="settings-description">Define franjas flexibles por día. Una franja que termina antes de empezar se interpreta como nocturna.</p></div></div>
                    @if ($errors->any())<div class="mx-6 mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert"><strong>Revisa los horarios.</strong> Comprueba que no falten horas ni existan solapamientos.</div>@endif
                    <div class="settings-card-body space-y-5">
                        @foreach ($contexts as $context => $contextLabel)
                            @if ($context === 'takeaway' && (! $restaurant->takeaway_enabled || $restaurant->takeaway_use_general_schedule)) @continue @endif
                            @if ($context === 'delivery' && (! $restaurant->delivery_enabled || $restaurant->delivery_use_general_schedule)) @continue @endif
                            <section class="schedule-context" data-context="{{ $context }}"><div class="flex items-start justify-between gap-3"><div><h3 class="font-semibold">{{ $contextLabel }}</h3><p class="mt-1 text-sm text-stone-500">{{ $context === 'general' ? 'El horario habitual de apertura del establecimiento.' : 'Horario específico, independiente del horario general.' }}</p></div><span class="status-pill">{{ $context === 'general' ? 'Base' : 'Personalizado' }}</span></div><div class="mt-5 space-y-3">
                                @foreach ($days as $weekday => $dayName)
                                    @php($day = $hours[$context][$weekday])
                                    <fieldset class="day-row" data-day data-weekday="{{ $weekday }}" data-context="{{ $context }}"><legend class="day-name">{{ $dayName }}</legend><div class="day-content"><label class="check-label"><input type="checkbox" name="hours[{{ $context }}][{{ $weekday }}][enabled]" value="1" data-day-toggle @checked($day['enabled'])> Abierto</label><div class="intervals" data-intervals @if (! $day['enabled']) hidden @endif>@foreach ($day['intervals'] as $index => $interval)<div class="interval-row" data-interval><div><label class="sr-only" for="{{ $context }}-{{ $weekday }}-{{ $index }}-opens">Apertura</label><input id="{{ $context }}-{{ $weekday }}-{{ $index }}-opens" type="time" name="hours[{{ $context }}][{{ $weekday }}][intervals][{{ $index }}][opens_at]" value="{{ $interval['opens_at'] }}" class="form-input"></div><span class="time-separator">a</span><div><label class="sr-only" for="{{ $context }}-{{ $weekday }}-{{ $index }}-closes">Cierre</label><input id="{{ $context }}-{{ $weekday }}-{{ $index }}-closes" type="time" name="hours[{{ $context }}][{{ $weekday }}][intervals][{{ $index }}][closes_at]" value="{{ $interval['closes_at'] }}" class="form-input"></div><button type="button" class="icon-button" data-remove-interval aria-label="Eliminar franja del {{ strtolower($dayName) }}">×</button></div>@endforeach</div><div class="day-actions" @if (! $day['enabled']) hidden @endif><button type="button" class="text-button" data-add-interval>Añadir franja</button><button type="button" class="text-button" data-copy-day>Copiar horario</button></div><p class="closed-label" data-closed @if ($day['enabled']) hidden @endif>Cerrado</p></div></fieldset>
                                @endforeach
                            </div></section>
                        @endforeach
                    </div>
                    <div class="settings-card-footer"><span class="form-dirty-label hidden">Cambios sin guardar</span><button type="submit" class="button-primary">Guardar horarios</button></div>
                </form>
            </div>
        </div>
    </div>

    <dialog id="copy-dialog" class="copy-dialog"><form method="dialog"><div class="flex items-start justify-between gap-5"><div><p class="eyebrow">Reutiliza un horario</p><h2 class="mt-1 text-xl font-semibold">Copiar horario</h2><p id="copy-description" class="mt-2 text-sm leading-6 text-stone-500"></p></div><button value="cancel" class="icon-button" aria-label="Cerrar">×</button></div><div id="copy-days" class="mt-6 space-y-2"></div><div class="mt-7 flex justify-end gap-3"><button value="cancel" class="button-secondary">Cancelar</button><button id="copy-confirm" value="default" class="button-primary">Copiar horario</button></div></form></dialog>
@endsection
