@extends('layouts.pos', ['title' => 'Caja'])
@section('content')
<div class="mx-auto max-w-3xl"><a class="text-button" href="{{ route('restaurant.pos', $restaurant) }}">← Mesas</a><h1 class="mt-5 text-3xl font-semibold">Caja</h1>
@if(session('status'))<div class="mt-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('status') }}</div>@endif @if($errors->any())<div class="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
@if(!$session)
<section class="mt-6 rounded-2xl border border-stone-200 bg-white p-6"><h2 class="text-xl font-semibold">Abrir {{ $register->name }}</h2><form method="POST" action="{{ route('restaurant.pos.cash.open', $restaurant) }}" class="mt-5 grid gap-3 sm:grid-cols-2">@csrf<input type="hidden" name="register_id" value="{{ $register->id }}"><input class="form-input" name="opening_float_minor" type="number" min="0" placeholder="Fondo inicial (céntimos)" required><select class="form-input" name="employee_id" required><option value="">Encargado</option>@foreach($restaurant->employees()->with('operationalRoles')->where('is_active', true)->get() as $employee)@if($employee->operationalRoles->contains('code', 'manager'))<option value="{{ $employee->id }}">{{ $employee->display_name }}</option>@endif @endforeach</select><input class="form-input" name="pin" type="password" inputmode="numeric" placeholder="PIN fresco" required><button class="button-primary sm:col-span-2">Abrir caja</button></form></section>
@else
<section class="mt-6 rounded-2xl border border-stone-200 bg-white p-6"><p class="text-sm text-stone-500">Sesión abierta desde {{ $session->opened_at->format('H:i') }}</p><h2 class="mt-1 text-xl font-semibold">Cerrar caja</h2><form method="POST" action="{{ route('restaurant.pos.cash.close', $restaurant) }}" class="mt-5 grid gap-3 sm:grid-cols-2">@csrf<input type="hidden" name="cash_session_id" value="{{ $session->id }}"><input class="form-input" name="declared_cash_minor" type="number" min="0" placeholder="Efectivo contado (céntimos)" required><input class="form-input" name="manager_employee_id" type="number" placeholder="ID encargado" required><input class="form-input" name="manager_pin" type="password" inputmode="numeric" placeholder="PIN fresco" required><button class="button-primary sm:col-span-2">Cerrar y arquear</button></form></section>
@endif</div>
@endsection
