@extends('layouts.app', ['title' => $modifierGroup ? 'Editar grupo' : 'Nuevo grupo', 'heading' => $modifierGroup ? 'Editar grupo' : 'Nuevo grupo'])
@php($editing = $modifierGroup !== null)
@section('content')
    <div class="max-w-3xl"><a href="{{ route('restaurant.menu.modifier-groups.index', $restaurant) }}" class="text-sm font-semibold text-orange-700">← Volver a modificadores</a><p class="eyebrow mt-8">Carta</p><h2 class="mt-1 text-3xl font-semibold tracking-tight">{{ $editing ? 'Edita un grupo compartido' : 'Crea un grupo reutilizable' }}</h2><p class="mt-3 text-stone-500">Las reglas y opciones de este grupo se aplicarán a todos los productos que lo utilicen.</p></div>
    @if ($editing && $modifierGroup->productAssignments()->count() > 0)<div class="mt-6 max-w-3xl rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-6 text-amber-900" role="note"><strong>Grupo compartido.</strong> Se utiliza en {{ $modifierGroup->productAssignments()->count() }} productos. Los cambios afectarán a todos.</div>@endif
    @if (session('status'))<div class="mt-6 max-w-3xl rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800" role="status">{{ session('status') }}</div>@endif
    @if ($errors->any())<div class="mt-6 max-w-3xl rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ $editing ? route('restaurant.menu.modifier-groups.update', [$restaurant, $modifierGroup]) : route('restaurant.menu.modifier-groups.store', $restaurant) }}" class="settings-card mt-8 max-w-3xl" data-dirty-form>@csrf @if ($editing) @method('PATCH') @endif
        <div class="settings-card-body grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label for="name" class="field-label">Nombre del grupo <span class="text-orange-600">*</span></label><input id="name" name="name" value="{{ old('name', $modifierGroup->name ?? '') }}" required class="form-input"></div><div class="sm:col-span-2"><label for="description" class="field-label">Ayuda para el cliente o equipo</label><textarea id="description" name="description" rows="2" class="form-input">{{ old('description', $modifierGroup->description ?? '') }}</textarea></div><div><label for="min_selections" class="field-label">Mínimo de elecciones</label><input id="min_selections" name="min_selections" type="number" min="0" max="50" value="{{ old('min_selections', $modifierGroup->min_selections ?? 0) }}" class="form-input"><p class="field-help">0 significa que el grupo es opcional.</p></div><div><label for="max_selections" class="field-label">Máximo de elecciones</label><input id="max_selections" name="max_selections" type="number" min="1" max="50" value="{{ old('max_selections', $modifierGroup->max_selections ?? 1) }}" class="form-input"><p class="field-help">1 representa una elección única. Vacío = sin límite.</p></div><label class="check-label"><input type="hidden" name="allow_quantities" value="0"><input type="checkbox" name="allow_quantities" value="1" @checked(old('allow_quantities', $modifierGroup->allow_quantities ?? false) == 1)> Permitir cantidades por opción</label><label class="check-label"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $modifierGroup->is_active ?? true) == 1)> Grupo activo</label></div>
        <div class="settings-card-footer"><span class="form-dirty-label hidden" role="status">Cambios sin guardar</span><a href="{{ route('restaurant.menu.modifier-groups.index', $restaurant) }}" class="button-secondary">Cancelar</a><button class="button-primary">{{ $editing ? 'Guardar grupo' : 'Crear grupo' }}</button></div>
    </form>
    @if ($editing)<div id="options" class="settings-card mt-8 max-w-3xl"><div class="settings-card-header"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="eyebrow">Opciones</p><h3 class="settings-title">Qué puede elegir el cliente</h3></div><a href="{{ route('restaurant.menu.modifier-groups.options.create', [$restaurant, $modifierGroup]) }}" class="button-secondary">Añadir opción</a></div></div><div class="settings-card-body">@if ($modifierGroup->options->isEmpty())<p class="text-sm text-stone-500">Añade la primera opción para completar este grupo.</p>@else<div class="space-y-2">@foreach ($modifierGroup->options as $index => $option)<div class="flex flex-wrap items-center gap-3 rounded-xl border border-stone-200 px-3 py-3"><div class="flex items-center gap-1"><form method="POST" action="{{ route('restaurant.menu.modifier-groups.options.move', [$restaurant, $modifierGroup, $option, 'up']) }}">@csrf @method('PATCH')<button class="icon-button" @disabled($index === 0)>↑</button></form><form method="POST" action="{{ route('restaurant.menu.modifier-groups.options.move', [$restaurant, $modifierGroup, $option, 'down']) }}">@csrf @method('PATCH')<button class="icon-button" @disabled($index === $modifierGroup->options->count() - 1)>↓</button></form></div><div class="min-w-0 flex-1"><p class="font-semibold">{{ $option->name }} @if (! $option->is_active)<span class="badge">Inactiva</span>@endif</p><p class="text-sm text-stone-500">{{ $option->price_delta_minor > 0 ? '+ '.\App\CatalogMoney::format($option->price_delta_minor).' '.$restaurant->currency : 'Sin suplemento' }} · Máximo x{{ $option->max_quantity }}</p></div><a href="{{ route('restaurant.menu.modifier-groups.options.edit', [$restaurant, $modifierGroup, $option]) }}" class="button-secondary">Editar</a></div>@endforeach</div>@endif</div></div>@endif
@endsection
