@extends('layouts.app', ['title' => 'Modificadores', 'heading' => 'Modificadores'])

@section('content')
    <div class="flex flex-wrap items-start justify-between gap-5"><div><p class="eyebrow">Carta</p><h2 class="mt-1 text-3xl font-semibold tracking-tight">Modificadores</h2><p class="mt-3 max-w-2xl text-stone-500">Reutiliza extras, salsas y preparaciones en varios productos sin configurarlos una y otra vez.</p></div><a href="{{ route('restaurant.menu.modifier-groups.create', $restaurant) }}" class="button-primary">Nuevo grupo</a></div>
    <div class="mt-8 flex gap-2 border-b border-stone-200"><a href="{{ route('restaurant.menu', $restaurant) }}" class="local-tab">Productos</a><a href="{{ route('restaurant.menu.categories.index', $restaurant) }}" class="local-tab">Categorías</a><a href="{{ route('restaurant.menu.modifier-groups.index', $restaurant) }}" class="local-tab local-tab-active" aria-current="page">Modificadores</a></div>
    @if (session('status'))<div class="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800" role="status">{{ session('status') }}</div>@endif
    @if ($errors->any())<div class="mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{{ $errors->first() }}</div>@endif
    @if ($groups->isEmpty())<section class="empty-panel mt-8"><span class="empty-icon">+</span><h3 class="mt-5 text-xl font-semibold">Todavía no hay grupos</h3><p class="mt-2 max-w-md text-sm leading-6 text-stone-500">Crea un grupo para representar un punto de cocción, una salsa o un conjunto de extras.</p><a href="{{ route('restaurant.menu.modifier-groups.create', $restaurant) }}" class="button-primary mt-6">Crear primer grupo</a></section>@else
        <div class="mt-6 space-y-3">@foreach ($groups as $group)<article class="flex flex-wrap items-center gap-4 rounded-2xl border border-stone-200 bg-white px-5 py-4"><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><a href="{{ route('restaurant.menu.modifier-groups.edit', [$restaurant, $group]) }}" class="font-semibold hover:text-orange-600">{{ $group->name }}</a>@if (! $group->is_active)<span class="badge">Inactivo</span>@endif</div><p class="mt-1 text-sm text-stone-500">{{ $group->min_selections ? 'Obligatorio' : 'Opcional' }} · {{ $group->max_selections === 1 ? 'Elige 1' : ($group->max_selections ? 'Hasta '.$group->max_selections : 'Sin límite') }} · {{ $group->options_count }} opciones · Usado en {{ $group->product_assignments_count }} productos</p></div><a href="{{ route('restaurant.menu.modifier-groups.edit', [$restaurant, $group]) }}" class="button-secondary">Editar</a><form method="POST" action="{{ route('restaurant.menu.modifier-groups.duplicate', [$restaurant, $group]) }}">@csrf<button class="text-button">Duplicar</button></form></article>@endforeach</div><div class="mt-5">{{ $groups->links() }}</div>
    @endif
@endsection
