@extends('layouts.app', ['title' => isset($format) ? 'Editar formato' : 'Nuevo formato', 'heading' => isset($format) ? 'Editar formato' : 'Nuevo formato'])
@php($editing = isset($format))
@section('content')
    <div class="max-w-2xl"><a href="{{ route('restaurant.menu.products.edit', [$restaurant, $product]) }}#formats" class="text-sm font-semibold text-orange-700">← Volver al producto</a><p class="eyebrow mt-8">{{ $product->name }}</p><h2 class="mt-1 text-3xl font-semibold tracking-tight">{{ $editing ? 'Editar formato' : 'Añadir formato' }}</h2><p class="mt-3 text-stone-500">Define el precio absoluto de esta presentación.</p></div>
    @if ($errors->any())<div class="mt-6 max-w-2xl rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ $editing ? route('restaurant.menu.products.formats.update', [$restaurant, $product, $format]) : route('restaurant.menu.products.formats.store', [$restaurant, $product]) }}" class="settings-card mt-8 max-w-2xl" data-dirty-form>@csrf @if ($editing) @method('PATCH') @endif
        <div class="settings-card-body grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label for="name" class="field-label">Nombre <span class="text-orange-600">*</span></label><input id="name" name="name" value="{{ old('name', $format->name ?? '') }}" required class="form-input"></div><div><label for="price" class="field-label">Precio ({{ $restaurant->currency }}) <span class="text-orange-600">*</span></label><input id="price" name="price" value="{{ old('price', isset($format) ? \App\CatalogMoney::format($format->price_minor) : '') }}" placeholder="5,00" required class="form-input"></div><div><label for="cost" class="field-label">Coste interno</label><input id="cost" name="cost" value="{{ old('cost', isset($format) && $format->cost_minor !== null ? \App\CatalogMoney::format($format->cost_minor) : '') }}" class="form-input"></div><label class="check-label"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $format->is_active ?? true) == 1)> Activo</label><label class="check-label"><input type="hidden" name="is_default" value="0"><input type="checkbox" name="is_default" value="1" @checked(old('is_default', $format->is_default ?? false) == 1)> Predeterminado</label></div>
        <div class="settings-card-footer"><span class="form-dirty-label hidden" role="status">Cambios sin guardar</span><a href="{{ route('restaurant.menu.products.edit', [$restaurant, $product]) }}#formats" class="button-secondary">Cancelar</a><button class="button-primary">Guardar formato</button></div>
    </form>
@endsection
