@extends('public.layout', ['title' => $restaurant->name.' · Carta'])
@section('content')
<header class="rounded-3xl bg-stone-950 p-6 text-white"><div class="flex items-center gap-3"><span class="flex size-12 items-center justify-center rounded-2xl bg-orange-500 text-xl font-bold">M</span><div><p class="text-sm text-orange-300">{{ $restaurant->name }}</p><h1 class="text-2xl font-semibold">Carta</h1></div></div>
@if($table)<p class="mt-5 rounded-xl bg-white/10 px-4 py-3 text-sm">Estás pidiendo desde <strong>{{ $table->name }}</strong> · {{ $table->zone->name }}</p>@endif</header>
<nav class="sticky top-0 z-10 -mx-4 mt-4 flex gap-2 overflow-x-auto bg-stone-50 px-4 py-2 sm:-mx-6 sm:px-6"><a class="rounded-full bg-orange-500 px-4 py-2 text-sm font-semibold text-white" href="#inicio">Carta</a><a class="rounded-full border border-stone-200 bg-white px-4 py-2 text-sm font-semibold" href="{{ $table ? route('public.qr.cart', $table->qr_token) : route('public.cart', [$restaurant, $channel]) }}">Carrito</a></nav>
@if(session('status'))<div class="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('status') }}</div>@endif
@if($errors->any())<div class="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<div id="inicio" class="mt-6 space-y-8">
@foreach($categories as $category)<section><h2 class="text-xl font-semibold">{{ $category->name }}</h2><div class="mt-3 grid gap-3">
@foreach($products->get($category->id, collect()) as $product)<article class="flex gap-4 rounded-2xl border border-stone-200 bg-white p-4">@if($product->image_path)<img class="size-24 shrink-0 rounded-xl object-cover" src="{{ asset('storage/'.$product->image_path) }}" alt="{{ $product->name }}" loading="lazy">@else<div class="flex size-24 shrink-0 items-center justify-center rounded-xl bg-orange-50 text-2xl font-semibold text-orange-500">{{ mb_strtoupper(mb_substr($product->name, 0, 1)) }}</div>@endif<div class="min-w-0 flex-1"><h3 class="font-semibold">{{ $product->name }} @if($product->track_stock && $product->stock_quantity <= 0)<span class="ml-1 rounded bg-red-100 px-2 py-0.5 text-xs font-semibold text-red-800">Agotado</span>@endif</h3>@if($product->description)<p class="mt-1 line-clamp-2 text-sm text-stone-500">{{ $product->description }}</p>@endif<p class="mt-2 font-semibold">{{ $product->formats->isNotEmpty() ? 'Desde ' : '' }}{{ \App\CatalogMoney::format($product->formats->where('is_active', true)->first()?->price_minor ?? $product->price_minor) }} {{ $restaurant->currency }}</p><a class="mt-3 inline-block text-sm font-semibold text-orange-700" href="{{ $table ? route('public.qr.product', [$table->qr_token, $product->id]) : route('public.product', [$restaurant, $channel, $product->id]) }}">Ver y añadir →</a></div></article>@endforeach</div></section>@endforeach</div>
@endsection
