@extends('layouts.app', ['title' => isset($modifierOption) ? 'Editar opción' : 'Nueva opción', 'heading' => isset($modifierOption) ? 'Editar opción' : 'Nueva opción'])
@php($editing = isset($modifierOption))
@section('content')
    <div class="max-w-2xl"><a href="{{ route('restaurant.menu.modifier-groups.edit', [$restaurant, $modifierGroup]) }}#options" class="text-sm font-semibold text-orange-700">← Volver al grupo</a><p class="eyebrow mt-8">{{ $modifierGroup->name }}</p><h2 class="mt-1 text-3xl font-semibold tracking-tight">{{ $editing ? 'Editar opción' : 'Añadir opción' }}</h2></div>
    @if ($errors->any())<div class="mt-6 max-w-2xl rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ $editing ? route('restaurant.menu.modifier-groups.options.update', [$restaurant, $modifierGroup, $modifierOption]) : route('restaurant.menu.modifier-groups.options.store', [$restaurant, $modifierGroup]) }}" class="settings-card mt-8 max-w-2xl" data-dirty-form>@csrf @if ($editing) @method('PATCH') @endif
        <div class="settings-card-body grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label for="name" class="field-label">Nombre <span class="text-orange-600">*</span></label><input id="name" name="name" value="{{ old('name', $modifierOption->name ?? '') }}" required class="form-input"></div><div><label for="supplement" class="field-label">Suplemento ({{ $restaurant->currency }})</label><input id="supplement" name="supplement" value="{{ old('supplement', isset($modifierOption) ? \App\CatalogMoney::format($modifierOption->price_delta_minor) : '0,00') }}" class="form-input"></div><div><label for="max_quantity" class="field-label">Cantidad máxima</label><input id="max_quantity" name="max_quantity" type="number" min="1" max="20" value="{{ old('max_quantity', $modifierOption->max_quantity ?? 1) }}" class="form-input"></div><div><label for="instruction" class="field-label">Indicaciones para cocina</label><select id="instruction" name="instruction" class="form-input"><option value="normal" @selected(old('instruction', $modifierOption->instruction ?? 'normal') === 'normal')>Normal</option><option value="highlight" @selected(old('instruction', $modifierOption->instruction ?? '') === 'highlight')>Destacar</option><option value="aside" @selected(old('instruction', $modifierOption->instruction ?? '') === 'aside')>Servir o preparar aparte</option></select></div><label class="check-label"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $modifierOption->is_active ?? true) == 1)> Opción activa</label></div>
        <div class="settings-card-footer"><span class="form-dirty-label hidden" role="status">Cambios sin guardar</span><a href="{{ route('restaurant.menu.modifier-groups.edit', [$restaurant, $modifierGroup]) }}#options" class="button-secondary">Cancelar</a><button class="button-primary">Guardar opción</button></div>
    </form>
@endsection
