@extends('layouts.app', ['title' => $employee->exists ? 'Editar empleado' : 'Nuevo empleado', 'heading' => 'Personal'])
@section('content')
<div class="max-w-3xl"><p class="eyebrow">Personal</p><h2 class="mt-1 text-3xl font-semibold tracking-tight">{{ $employee->exists ? 'Editar empleado' : 'Nuevo empleado' }}</h2><p class="mt-3 text-stone-500">El empleado no necesita una cuenta SaaS para trabajar operativamente.</p></div>
@include('staff.partials.local-nav')
<form method="POST" action="{{ $employee->exists ? route('restaurant.staff.employees.update', [$restaurant, $employee]) : route('restaurant.staff.employees.store', $restaurant) }}" class="mt-8 max-w-3xl rounded-2xl border border-stone-200 bg-white"><div class="settings-card-body grid gap-5 sm:grid-cols-2">@csrf @if($employee->exists) @method('PATCH') @endif
<div><label class="field-label" for="first_name">Nombre</label><input class="form-input" id="first_name" name="first_name" required value="{{ old('first_name', $employee->first_name) }}">@error('first_name')<p class="field-message">{{ $message }}</p>@enderror</div><div><label class="field-label" for="last_name">Apellidos</label><input class="form-input" id="last_name" name="last_name" value="{{ old('last_name', $employee->last_name) }}"></div><div><label class="field-label" for="display_name">Nombre operativo</label><input class="form-input" id="display_name" name="display_name" required maxlength="80" value="{{ old('display_name', $employee->display_name) }}"><p class="field-help">Es el nombre grande que verá el TPV.</p></div><div><label class="field-label" for="phone">Teléfono</label><input class="form-input" id="phone" name="phone" value="{{ old('phone', $employee->phone) }}"></div><div><label class="field-label" for="email">Email opcional</label><input class="form-input" id="email" type="email" name="email" value="{{ old('email', $employee->email) }}"></div><div><label class="field-label" for="user_id">Vincular cuenta SaaS</label><select class="form-input" id="user_id" name="user_id"><option value="">Sin cuenta vinculada</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(old('user_id', $employee->user_id) == $user->id)>{{ $user->name }} · {{ $user->email }}</option>@endforeach</select><p class="field-help">Solo aparecen usuarios con acceso a este restaurante.</p></div>
<fieldset class="sm:col-span-2"><legend class="field-label">Funciones operativas</legend><div class="grid gap-3 sm:grid-cols-2">@foreach($roles as $role)<label class="check-label"><input type="checkbox" name="roles[]" value="{{ $role->id }}" @checked(in_array($role->id, old('roles', $employee->operationalRoles->pluck('id')->all()), true))> {{ $role->name }}</label>@endforeach</div>@error('roles')<p class="field-message">{{ $message }}</p>@enderror</fieldset>
<div><label class="field-label" for="pin">{{ $employee->hasPin() ? 'Cambiar PIN' : 'PIN operativo' }}</label><input class="form-input" id="pin" name="pin" inputmode="numeric" pattern="[0-9]{4,8}" maxlength="8" placeholder="4–8 cifras"><p class="field-help">Nunca se mostrará el PIN guardado.</p>@error('pin')<p class="field-message">{{ $message }}</p>@enderror</div>@if($employee->hasPin())<label class="check-label self-end"><input type="checkbox" name="remove_pin" value="1"> Retirar PIN operativo</label>@endif
<label class="check-label sm:col-span-2"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $employee->exists ? $employee->is_active : true))> Empleado activo</label>
</div><div class="settings-card-footer flex justify-between"><a class="button-secondary" href="{{ route('restaurant.staff.employees.index', $restaurant) }}">Cancelar</a><button class="button-primary">Guardar empleado</button></div></form>
@endsection
