@extends('layouts.app', ['title' => 'Personal', 'heading' => 'Personal'])
@section('content')
<div class="flex flex-wrap items-start justify-between gap-5"><div><p class="eyebrow">Personal</p><h2 class="mt-1 text-3xl font-semibold tracking-tight">Empleados</h2><p class="mt-3 max-w-2xl text-stone-500">Identidades operativas independientes de las cuentas de Marchando.</p></div>@if($canManage)<a href="{{ route('restaurant.staff.employees.create', $restaurant) }}" class="button-primary">Nuevo empleado</a>@endif</div>
@include('staff.partials.local-nav')
@if(session('status'))<div class="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800" role="status">{{ session('status') }}</div>@endif
@if($errors->any())<div class="mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{{ $errors->first() }}</div>@endif
<form method="GET" class="mt-8 grid gap-3 rounded-2xl border border-stone-200 bg-white p-4 sm:grid-cols-4 sm:items-end"><div class="sm:col-span-2"><label class="field-label" for="q">Buscar</label><input class="form-input" id="q" name="q" value="{{ request('q') }}" placeholder="Nombre operativo…"></div><div><label class="field-label" for="role">Función</label><select class="form-input" id="role" name="role"><option value="">Todas</option>@foreach($roles as $role)<option value="{{ $role->id }}" @selected(request('role') == $role->id)>{{ $role->name }}</option>@endforeach</select></div><div><label class="field-label" for="state">Estado</label><select class="form-input" id="state" name="state"><option value="">Todos</option><option value="active" @selected(request('state') === 'active')>Activos</option><option value="inactive" @selected(request('state') === 'inactive')>Inactivos</option></select></div><div class="sm:col-span-4 flex gap-2"><button class="button-primary">Filtrar</button><a class="button-secondary" href="{{ route('restaurant.staff.employees.index', $restaurant) }}">Limpiar</a></div></form>
<div class="mt-6 space-y-3">@forelse($employees as $employee)<article class="rounded-2xl border border-stone-200 bg-white p-5 {{ !$employee->is_active ? 'opacity-70' : '' }}"><div class="flex flex-wrap items-start justify-between gap-4"><div><div class="flex flex-wrap items-center gap-2"><h3 class="text-lg font-semibold">{{ $employee->display_name }}</h3>@if(!$employee->is_active)<span class="badge">Inactivo</span>@endif @if($employee->hasPin())<span class="badge badge-orange">PIN operativo</span>@else<span class="badge">Sin PIN</span>@endif @if($employee->open_intervals_count)<span class="badge">Trabajando</span>@endif</div><p class="mt-1 text-sm text-stone-500">{{ $employee->first_name }} {{ $employee->last_name }} · {{ $employee->roleNames() ?: 'Sin función' }}</p></div><div class="flex gap-3"><a class="text-button" href="{{ route('restaurant.staff.employees.show', [$restaurant, $employee]) }}">Ficha</a>@if($canManage)<a class="text-button" href="{{ route('restaurant.staff.employees.edit', [$restaurant, $employee]) }}">Editar</a>@endif</div></div></article>@empty<div class="empty-panel">No hay empleados que coincidan con los filtros.</div>@endforelse</div><div class="mt-6">{{ $employees->links() }}</div>
@endsection
