@extends('layouts.app', ['title' => 'Mesas', 'heading' => 'Mesas'])
@section('content')
<div class="flex flex-wrap items-start justify-between gap-5"><div><p class="eyebrow">Operación</p><h2 class="mt-1 text-3xl font-semibold tracking-tight">Mesas</h2><p class="mt-3 max-w-2xl text-stone-500">Consulta rápidamente la distribución de {{ $restaurant->name }}.</p></div>@if($canManage)<a href="{{ route('restaurant.restaurant.manage', $restaurant) }}" class="button-secondary">Administrar zonas y mesas</a>@endif</div>
@include('restaurant.partials.local-nav')
<nav class="mt-6 flex gap-2 overflow-x-auto pb-1" aria-label="Filtrar mesas por zona"><a href="{{ route('restaurant.restaurant', $restaurant) }}" class="zone-filter {{ !$selectedZone ? 'zone-filter-active' : '' }}">Todas <span>{{ $allZones->sum(fn($zone) => $zone->diningTables()->where('is_active', true)->count()) }}</span></a>@foreach($allZones as $zone)<a href="{{ route('restaurant.restaurant', ['restaurant' => $restaurant, 'zone' => $zone->id]) }}" class="zone-filter {{ $selectedZone === $zone->id ? 'zone-filter-active' : '' }}">{{ $zone->name }} <span>{{ $zone->diningTables()->where('is_active', true)->count() }}</span></a>@endforeach</nav>
@if($zones->isEmpty())<section class="empty-panel mt-8"><span class="empty-icon">⌂</span><h3 class="mt-5 text-xl font-semibold">Todavía no hay mesas activas</h3><p class="mt-2 text-sm text-stone-500">Configura zonas y mesas para ver aquí el plano operativo.</p>@if($canManage)<a href="{{ route('restaurant.restaurant.manage', $restaurant) }}" class="button-primary mt-6">Configurar mesas</a>@endif</section>@else
<div class="mt-8 space-y-8">@foreach($zones as $zone)<section aria-labelledby="zone-{{ $zone->id }}"><div class="flex flex-wrap items-end justify-between gap-3"><div><h3 id="zone-{{ $zone->id }}" class="text-xl font-semibold">{{ $zone->name }}</h3><p class="mt-1 text-sm text-stone-500">{{ $zone->diningTables->count() }} {{ $zone->diningTables->count() === 1 ? 'mesa activa' : 'mesas activas' }} · {{ $zone->diningTables->sum('capacity') }} plazas</p></div></div><div class="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">@foreach($zone->diningTables as $table) @if($table->activeAssignment?->order)<a href="{{ route('restaurant.pos.orders.show', [$restaurant, $table->activeAssignment->order]) }}" class="table-card block"><div class="flex items-start justify-between gap-3"><span class="table-marker">{{ substr($table->name, 0, 1) }}</span><span class="badge badge-orange">Ocupada</span></div><h4 class="mt-5 text-lg font-semibold">{{ $table->name }}</h4><p class="mt-1 text-sm text-stone-500">{{ \App\CatalogMoney::format($table->activeAssignment->order->total_minor) }} € · {{ $table->activeAssignment->order->currentEmployee?->display_name }}</p></a>@else<a href="{{ route('restaurant.pos.tables.open', [$restaurant, $table]) }}" class="table-card block"><div class="flex items-start justify-between gap-3"><span class="table-marker">{{ substr($table->name, 0, 1) }}</span><span class="badge">{{ $table->capacity ? $table->capacity.' plazas' : 'Capacidad no indicada' }}</span></div><h4 class="mt-5 text-lg font-semibold">{{ $table->name }}</h4><p class="mt-1 text-sm text-stone-500">Libre · Abrir en TPV</p></a>@endif @endforeach</div></section>@endforeach</div>
@endif
@endsection
