<!doctype html>
<html lang="es">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Factura {{ $document->reference }}</title><style>body{font-family:system-ui,sans-serif;max-width:720px;margin:0 auto;padding:32px;color:#111}table{width:100%;border-collapse:collapse;font-size:14px}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}td.n,th.n{text-align:right}.grid{display:flex;gap:24px}.grid>div{flex:1;border:1px solid #ddd;border-radius:12px;padding:16px}.total{font-size:20px;font-weight:700}@media print{.noprint{display:none}}</style></head>
<body>
<h1>Factura {{ $document->reference }}</h1>
<p>Fecha de expedición: {{ $document->issued_at?->format('d/m/Y') }} · Venta #{{ $document->order_id }}</p>
<div class="grid"><div><h2>Emisor</h2><p><strong>{{ $document->snapshot['restaurant']['legal_name'] ?? $document->snapshot['restaurant']['name'] }}</strong><br>{{ $document->snapshot['restaurant']['tax_id'] }}<br>{{ $document->snapshot['restaurant']['address'] }} · {{ $document->snapshot['restaurant']['postal_code'] }} {{ $document->snapshot['restaurant']['city'] }}</p></div><div><h2>Destinatario</h2><p><strong>{{ $document->snapshot['customer']['legal_name'] ?? $document->snapshot['customer']['display_name'] }}</strong><br>{{ $document->snapshot['customer']['tax_id'] }}<br>{{ $document->snapshot['customer']['fiscal_address'] }} · {{ $document->snapshot['customer']['postal_code'] }} {{ $document->snapshot['customer']['city'] }}</p></div></div>
<table style="margin-top:24px"><thead><tr><th>Concepto</th><th class="n">Cant.</th><th class="n">Importe</th></tr></thead><tbody>@foreach ($document->snapshot['lines'] as $line)<tr><td>{{ $line['product_name'] }}@if ($line['format_name']) · {{ $line['format_name'] }}@endif</td><td class="n">{{ $line['active_quantity'] }}</td><td class="n">{{ \App\CatalogMoney::format($line['net_minor']) }} €</td></tr>@endforeach</tbody></table>
<p>Subtotal: {{ \App\CatalogMoney::format($document->subtotal_minor) }} € · Descuento: -{{ \App\CatalogMoney::format($document->discount_minor) }} € · Cargos: {{ \App\CatalogMoney::format($document->charges_minor) }} €</p>
<table><thead><tr><th>IVA</th><th class="n">Base</th><th class="n">Cuota</th></tr></thead><tbody>@foreach ($document->tax_breakdown as $tax)<tr><td>{{ $tax['rate'] === null ? 'Sin IVA' : $tax['rate'].' %' }}</td><td class="n">{{ \App\CatalogMoney::format($tax['base_minor']) }} €</td><td class="n">{{ \App\CatalogMoney::format($tax['tax_minor']) }} €</td></tr>@endforeach</tbody></table>
<p class="total">Total: {{ \App\CatalogMoney::format($document->total_minor) }} {{ $document->currency }}</p>
@if(isset($fiscal) && $fiscal)<div style="margin-top:24px;border:1px solid #ddd;border-radius:12px;padding:16px"><p><strong>QR tributario</strong></p><img src="{{ route('restaurant.fiscal.qr', [$restaurant, $fiscal->id]) }}" alt="QR tributario" width="180"><p style="font-size:12px">Factura verificable en la sede electrónica de la AEAT · VERI*FACTU ({{ $fiscal->environment === 'live' ? 'producción' : 'pruebas' }}) · {{ $fiscal->status }}</p></div>@endif
<p class="noprint"><button onclick="window.print()">Imprimir / guardar PDF</button></p>
</body>
</html>
