@extends('layouts.app', ['title' => $product ? 'Editar producto' : 'Nuevo producto', 'heading' => $product ? 'Editar producto' : 'Nuevo producto'])

@php
    $editing = $product !== null;
    $productAllergens = $product?->allergens->pluck('id')->all() ?? [];
    $price = $product ? \App\CatalogMoney::format($product->price_minor) : '';
    $cost = $product?->cost_minor !== null ? \App\CatalogMoney::format($product->cost_minor) : '';
@endphp
@section('content')
    <div class="max-w-3xl"><a href="{{ route('restaurant.menu', $restaurant) }}" class="text-sm font-semibold text-orange-700">← Volver a la carta</a><p class="eyebrow mt-8">Carta</p><h2 class="mt-1 text-3xl font-semibold tracking-tight">{{ $editing ? 'Edita el producto' : 'Nuevo producto' }}</h2><p class="mt-3 text-stone-500">Configura la información que necesitará tu equipo para venderlo correctamente.</p></div>
    @if ($errors->any())<div class="mt-6 max-w-3xl rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ $editing ? route('restaurant.menu.products.update', [$restaurant, $product]) : route('restaurant.menu.products.store', $restaurant) }}" enctype="multipart/form-data" class="settings-card mt-8 max-w-3xl" data-dirty-form>
        @csrf @if ($editing) @method('PATCH') @endif
        <div class="settings-card-header"><p class="eyebrow">Información básica</p><h3 class="settings-title">Qué estás ofreciendo</h3></div>
        <div class="settings-card-body grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label for="name" class="field-label">Nombre <span class="text-orange-600">*</span></label><input id="name" name="name" value="{{ old('name', $product->name ?? '') }}" required class="form-input"></div><div><label for="short_name" class="field-label">Nombre corto <span class="font-normal text-stone-400">(opcional)</span></label><input id="short_name" name="short_name" value="{{ old('short_name', $product->short_name ?? '') }}" class="form-input"><p class="field-help">Útil para TPV o impresión.</p></div><div><label for="category_id" class="field-label">Categoría <span class="text-orange-600">*</span></label><select id="category_id" name="category_id" required class="form-input"><option value="">Selecciona una categoría</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $product->category_id ?? '') == $category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="sm:col-span-2"><label for="description" class="field-label">Descripción</label><textarea id="description" name="description" rows="4" class="form-input">{{ old('description', $product->description ?? '') }}</textarea></div><label class="check-label"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $product->is_active ?? true))> Producto activo</label><label class="check-label"><input type="hidden" name="is_available" value="0"><input type="checkbox" name="is_available" value="1" @checked(old('is_available', $product->is_available ?? true))> Disponible ahora</label><label class="check-label"><input type="hidden" name="track_stock" value="0"><input type="checkbox" name="track_stock" value="1" @checked(old('track_stock', $product->track_stock ?? false))> Gestionar stock</label><p class="field-help sm:col-span-2">Con stock activado, las cantidades se gestionan desde Analítica → Stock con trazabilidad. A 0 se muestra agotado y bloquea la venta.</p></div>
        <div class="settings-subsection"><p class="eyebrow">Precio</p><h3 class="mt-1 text-base font-semibold">Venta y coste interno</h3><div class="mt-5 grid gap-5 sm:grid-cols-2"><div><label for="price" class="field-label">Precio de venta (€) <span class="text-orange-600">*</span></label><input id="price" name="price" inputmode="decimal" placeholder="9,50" value="{{ old('price', $price) }}" required class="form-input"></div><div><label for="cost" class="field-label">Coste interno (€)</label><input id="cost" name="cost" inputmode="decimal" placeholder="Opcional" value="{{ old('cost', $cost) }}" class="form-input"></div><div><label for="vat_rate" class="field-label">IVA (%)</label><input id="vat_rate" name="vat_rate" type="number" step="0.01" min="0" max="100" value="{{ old('vat_rate', $product->vat_rate ?? '') }}" class="form-input"><p class="field-help">Vacío = hereda el IVA del restaurante ({{ $restaurant->default_vat !== null ? $restaurant->default_vat.' %' : 'no configurado' }}).</p></div></div></div>
        <div class="settings-subsection"><p class="eyebrow">Canales</p><h3 class="mt-1 text-base font-semibold">Dónde se puede vender</h3><div class="mt-5 flex flex-wrap gap-4"><label class="check-label"><input type="hidden" name="available_dine_in" value="0"><input type="checkbox" name="available_dine_in" value="1" @checked(old('available_dine_in', $product->available_dine_in ?? $restaurant->dine_in_enabled))> Local</label>@if ($restaurant->takeaway_enabled)<label class="check-label"><input type="hidden" name="available_takeaway" value="0"><input type="checkbox" name="available_takeaway" value="1" @checked(old('available_takeaway', $product->available_takeaway ?? true))> Take Away</label>@endif @if ($restaurant->delivery_enabled)<label class="check-label"><input type="hidden" name="available_delivery" value="0"><input type="checkbox" name="available_delivery" value="1" @checked(old('available_delivery', $product->available_delivery ?? true))> Delivery</label>@endif</div><p class="field-help">Un canal desactivado en la configuración del restaurante nunca estará disponible, aunque el producto lo tenga marcado.</p></div>
        <div class="settings-subsection"><p class="eyebrow">Información alimentaria</p><h3 class="mt-1 text-base font-semibold">Alérgenos</h3><p class="mt-2 text-sm leading-6 text-stone-500">Marca únicamente los alérgenos declarados por el restaurante. Esto no sustituye los protocolos de contaminación cruzada.</p><div class="mt-5 grid gap-3 sm:grid-cols-2">@foreach ($allergens as $allergen)<label class="check-label rounded-lg border border-stone-200 px-3 py-2"><input type="checkbox" name="allergen_ids[]" value="{{ $allergen->id }}" @checked(in_array($allergen->id, old('allergen_ids', $productAllergens)))> {{ $allergen->name }}</label>@endforeach</div></div>
        <div class="settings-subsection"><p class="eyebrow">Multimedia</p><h3 class="mt-1 text-base font-semibold">Imagen principal</h3><div class="mt-5 flex flex-wrap items-start gap-5">@if ($product?->image_path)<img src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($product->image_path) }}" alt="Imagen actual de {{ $product->name }}" class="size-28 rounded-xl object-cover"><label class="check-label"><input type="checkbox" name="remove_image" value="1"> Eliminar imagen actual</label>@endif<div><label for="image" class="field-label">{{ $product?->image_path ? 'Reemplazar imagen' : 'Subir imagen' }}</label><input id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp" class="form-input"><p class="field-help">JPG, PNG o WebP. Máximo 5 MB.</p></div></div></div>
        <div class="settings-subsection"><p class="eyebrow">Producción</p><h3 class="mt-1 text-base font-semibold">Estación de cocina</h3><select class="form-input mt-4" name="kitchen_station_id"><option value="">Sin asignar</option>@foreach($stations as $station)<option value="{{ $station->id }}" @selected(old('kitchen_station_id', $product->kitchen_station_id ?? '') == $station->id)>{{ $station->name }}</option>@endforeach</select><p class="field-help">Las comandas sin estación aparecen en la cola «Sin asignar».</p></div><div class="settings-subsection"><p class="eyebrow">TPV</p><h3 class="mt-1 text-base font-semibold">Precio manual</h3><label class="check-label mt-4"><input type="hidden" name="allows_manual_price" value="0"><input type="checkbox" name="allows_manual_price" value="1" @checked(old('allows_manual_price', $product->allows_manual_price ?? false))> Permitir precio manual autorizado</label><p class="field-help">Solo un encargado podrá cambiar el precio de esta línea sin modificar el catálogo.</p></div><div class="settings-card-footer"><span class="form-dirty-label hidden" role="status">Cambios sin guardar</span><a href="{{ route('restaurant.menu', $restaurant) }}" class="button-secondary">Cancelar</a><button class="button-primary">{{ $editing ? 'Guardar cambios' : 'Crear producto' }}</button></div>
    </form>
    @if ($editing)
        <div class="settings-card mt-8 max-w-3xl">@include('menu.products.partials.formats')</div>
        <div class="settings-card mt-8 max-w-3xl">@include('menu.products.partials.modifier-groups')</div>
    @endif
@endsection
