@extends('layouts.app', ['title' => $category ? 'Editar categoría' : 'Nueva categoría', 'heading' => $category ? 'Editar categoría' : 'Nueva categoría'])

@php($editing = $category !== null)
@section('content')
    <div class="max-w-3xl"><a href="{{ route('restaurant.menu.categories.index', $restaurant) }}" class="text-sm font-semibold text-orange-700">← Volver a categorías</a><p class="eyebrow mt-8">Carta</p><h2 class="mt-1 text-3xl font-semibold tracking-tight">{{ $editing ? 'Edita la categoría' : 'Crea una categoría' }}</h2><p class="mt-3 text-stone-500">Una sección clara ayuda a tu equipo a encontrar la oferta rápidamente.</p></div>
    @if ($errors->any())<div class="mt-6 max-w-3xl rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ $editing ? route('restaurant.menu.categories.update', [$restaurant, $category]) : route('restaurant.menu.categories.store', $restaurant) }}" enctype="multipart/form-data" class="settings-card mt-8 max-w-3xl" data-dirty-form>
        @csrf @if ($editing) @method('PATCH') @endif
        <div class="settings-card-body grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label for="name" class="field-label">Nombre <span class="text-orange-600">*</span></label><input id="name" name="name" value="{{ old('name', $category->name ?? '') }}" required class="form-input">@error('name')<p class="field-message">{{ $message }}</p>@enderror</div><div class="sm:col-span-2"><label for="description" class="field-label">Descripción</label><textarea id="description" name="description" rows="3" class="form-input">{{ old('description', $category->description ?? '') }}</textarea></div><label class="check-label"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $category->is_active ?? true))> Categoría activa</label><div class="sm:col-span-2"><p class="field-label">Canales disponibles</p><div class="flex flex-wrap gap-4"><label class="check-label"><input type="hidden" name="available_dine_in" value="0"><input type="checkbox" name="available_dine_in" value="1" @checked(old('available_dine_in', $category->available_dine_in ?? $restaurant->dine_in_enabled))> Local</label>@if ($restaurant->takeaway_enabled)<label class="check-label"><input type="hidden" name="available_takeaway" value="0"><input type="checkbox" name="available_takeaway" value="1" @checked(old('available_takeaway', $category->available_takeaway ?? true))> Take Away</label>@endif @if ($restaurant->delivery_enabled)<label class="check-label"><input type="hidden" name="available_delivery" value="0"><input type="checkbox" name="available_delivery" value="1" @checked(old('available_delivery', $category->available_delivery ?? true))> Delivery</label>@endif</div></div><div><label for="image" class="field-label">Imagen principal</label><input id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp" class="form-input"><p class="field-help">JPG, PNG o WebP. Máximo 5 MB.</p>@if ($category?->image_path)<label class="check-label mt-3"><input type="checkbox" name="remove_image" value="1"> Eliminar imagen actual</label>@endif</div></div>
        <div class="settings-card-footer"><span class="form-dirty-label hidden" role="status">Cambios sin guardar</span><a href="{{ route('restaurant.menu.categories.index', $restaurant) }}" class="button-secondary">Cancelar</a><button class="button-primary">{{ $editing ? 'Guardar cambios' : 'Crear categoría' }}</button></div>
    </form>
@endsection
