@extends('layouts.app', ['title' => 'Categorías', 'heading' => 'Categorías'])

@section('content')
    <div class="flex flex-wrap items-start justify-between gap-5"><div><p class="eyebrow">Catálogo</p><h2 class="mt-1 text-3xl font-semibold tracking-tight">Categorías</h2><p class="mt-3 text-stone-500">Ordena la carta y activa solo las secciones que quieres ofrecer.</p></div><div class="flex gap-3"><a href="{{ route('restaurant.menu', $restaurant) }}" class="button-secondary">Ver productos</a>@if ($canManage)<a href="{{ route('restaurant.menu.categories.create', $restaurant) }}" class="button-primary">Nueva categoría</a>@endif</div></div>
    @if (session('status'))<div class="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800" role="status">{{ session('status') }}</div>@endif
    @if ($errors->any())<div class="mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" role="alert">{{ $errors->first() }}</div>@endif
    <div class="mt-8 flex gap-2 border-b border-stone-200"><a href="{{ route('restaurant.menu', $restaurant) }}" class="local-tab">Productos</a><a href="{{ route('restaurant.menu.categories.index', $restaurant) }}" class="local-tab local-tab-active" aria-current="page">Categorías</a><a href="{{ route('restaurant.menu.modifier-groups.index', $restaurant) }}" class="local-tab">Modificadores</a></div>
    @if ($categories->isEmpty())<section class="empty-panel mt-8"><span class="empty-icon">+</span><h3 class="mt-5 text-xl font-semibold">Todavía no hay categorías</h3><p class="mt-2 text-sm text-stone-500">Crea la primera sección de tu carta para empezar a añadir productos.</p><a href="{{ route('restaurant.menu.categories.create', $restaurant) }}" class="button-primary mt-6">Crear categoría</a></section>@else
        <div class="mt-6 space-y-3">@foreach ($categories as $index => $category)<article class="flex flex-wrap items-center gap-4 rounded-2xl border border-stone-200 bg-white px-5 py-4"><div class="flex size-10 shrink-0 items-center justify-center rounded-xl bg-orange-50 font-semibold text-orange-700">{{ $index + 1 }}</div><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><a href="{{ route('restaurant.menu', ['restaurant' => $restaurant, 'category' => $category->id]) }}" class="font-semibold hover:text-orange-600">{{ $category->name }}</a>@if (! $category->is_active)<span class="badge">Inactiva</span>@endif</div><p class="mt-1 text-sm text-stone-500">{{ $category->description ?: 'Sin descripción' }} · {{ $category->products_count }} {{ $category->products_count === 1 ? 'producto' : 'productos' }}</p></div>@if ($canManage)<div class="flex items-center gap-1"><form method="POST" action="{{ route('restaurant.menu.categories.move', [$restaurant, $category, 'up']) }}">@csrf @method('PATCH')<button class="icon-button" aria-label="Subir {{ $category->name }}">↑</button></form><form method="POST" action="{{ route('restaurant.menu.categories.move', [$restaurant, $category, 'down']) }}">@csrf @method('PATCH')<button class="icon-button" aria-label="Bajar {{ $category->name }}">↓</button></form><a href="{{ route('restaurant.menu.categories.edit', [$restaurant, $category]) }}" class="button-secondary ml-2">Editar</a></div>@endif</article>@endforeach</div>
    @endif
@endsection
